### ISSUE TITLE
Reason for having misp_tag.py

### ISSUE THREAD

**Issue by jaegeral** [DCSO/tie2misp#10]
I am not sure if it really makes sense to have misp_tag, misp_event and misp_attribute as a class, as they implement more or less only things that are already in pyMISP.

For me that looks over engineered without a real need and decreases flexibility.

**Comment by Mezzonian** [comment]
This is a good point. At first sight it really looks a little bit over engineerd but the reason for the implementation was the creation of a data model, with which all processed data can be written directly into a JSON file and / or all data can be uploaded directly via pymisp. For both, the serialization and upload function is available in all child classes to make the use easy for further implementations and it keeps the implementation a little bit independently.

However, I will look at the PyMISP implementation and see if I can throw unnecessary redundancies out or make things easier.

**Comment by Mezzonian** [comment]
After adding tagging in tie2misp, the misp_tag.py is not used anymore and will be deleted in the next merge. I will keep an eye on misp_event and misp_attribute in further commits and try to improve some things there.
